### PR TITLE
Implement support for `test_suffixes_excludes`

### PR DESCRIPTION
**Pull request by guw**
This addresses #215

### CODE REVIEW

**Comment by guw** [comment]
@illicitonion @shs96c Can we can this reviewed? 🙏

**Review by shs96c — APPROVED** [review]
LGTM. Thank you for the PR!

**Comment by shs96c** [comment]
@guw, I'm happy to merge this, but I think there's a conflict in the `.gitignore` file. Would you be able to resolve this?

**Comment by guw** [comment]
@shs96c Done. Thanks!

**Pull request merged**
