### PR TITLE
lock file for maven in bzlmod

### PR DESCRIPTION
**Pull request by firov**
https://github.com/bazel-contrib/rules_jvm/issues/251

Existing frozen_deps_install.json doesn't match contrib_rules_jvm_deps_install.json generated by bzlmod version of maven.install, so i think we can replace old one only after full migration to bzlmod and use single version of maven.install

### CODE REVIEW

**Review by illicitonion — APPROVED** [review]
Thanks!

**Comment by firov** [comment]
@illicitonion hey can you please reapprove, fixed tests

**Comment by firov** [comment]
Fixed gazelle test, sadly i can't launch pr checks myself.

**Comment by illicitonion** [comment]
After your first PR gets merged, CI will run automatically for future PRs :) Thanks for your patience!

**Pull request merged**
