### PR TITLE
Add support for transforming Checkstyle XML output to JUnit XML

### PR DESCRIPTION
**Pull request by fzakaria**
Bazel will natively create a `test.xml` for all test runners if they do not create one themselves.

For the checkstyle test-runner it would create a test.xml that captures the system-out.
```xml
<testsuites>
  <testsuite name="server-common/server-common-checkstyleexec" tests="1" failures="0" errors="1">
    <testcase name="server-common/server-common-checkstyleexec" status="run" duration="5" time="5"><error message="exited with error code 1"></error></testcase>
      <system-out>
Generated test.log (if the file is not UTF-8, then this may be unreadable):
<![CDATA[exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //server-common:server-common-checkstyle
-----------------------------------------------------------------------------
Checkstyle ends with 1 errors.
Starting audit...
[ERROR] server-common/src/main/java/org/apache/kafka/queue/KafkaEventQueue.java:30:1: Disallowed import - io.confluent.kafka.util.OpenTelemetryManager. [ImportControl]
Audit done.]]>
      </system-out>
    </testsuite>
</testsuites>
```

JUnit is a well establish format and well known by many CI programs.
Having the checkstyle rule itself create a more curated JUnit XML file is in the user's best interest.

In this PR, we modify the checkstyle rules to emit a `test.xml` itself, stopping Bazel from implicitly doing so.
We have checkstyle emit the XML format _always_ and then use a very minimal Java tool and a provided default XLST (XML stylesheet) to transform the Checkstyle XML to one following JUnit's XML specification.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
<testsuite package="Checkstyle" name="src/main/java/io/confluent/utils/HelloWorldUtils.java" tests="2" errors="2">

<testcase name="com.puppycrawl.tools.checkstyle.checks.imports.AvoidStarImportCheck" classname="src/main/java/io/confluent/utils/HelloWorldUtils.java">
    <error type="com.puppycrawl.tools.checkstyle.checks.imports.AvoidStarImportCheck" message="Line 3: Using the '.*' form of import should be avoided - java.io.*."/>
</testcase>

<testcase name="com.puppycrawl.tools.checkstyle.checks.javadoc.MissingJavadocMethodCheck" classname="src/main/java/io/confluent/utils/HelloWorldUtils.java">
    <error type="com.puppycrawl.tools.checkstyle.checks.javadoc.MissingJavadocMethodCheck" message="Line 7: Missing a Javadoc comment."/>
</testcase>

</testsuite>
</testsuites>
```

### CODE REVIEW

**Comment by fzakaria** [comment]
Looks like the previous result failed on some format errors; I've ran the formatters buildifier and google-java-format

**Review by shs96c — APPROVED** [review]
Apologies for taking so long to review this: we needed to fix the CI tests first, and that took longer than expected. Thank you for your patience.

**Comment by shs96c** [comment]
You may need to rebase past e7361064781d8c23a67b41d2b61188d80c516058 and re-run the `./tools/format.sh` script to get a clean test run.

**Comment by fzakaria** [comment]
@shs96c  I rebased and ran the formatter again.
It forces the names of my target so I needed to change it for that (seems a bit over-zealous but /shrug)

Also, I think there is an escape impurity.
I had to do `CC=$(which clang) ./tools/format.sh` since my `cc` was set to `gcc` and it would give me the error:
```
gcc: error: unrecognized command line option '-fobjc-link-runtime'
```

**Comment by fzakaria** [comment]
The windows issue looks transient.

**Review by gibfahn — APPROVED** [review]

**Comment by gibfahn** [comment]
(retrying the tests)

**Pull request merged**
